### ISSUE TITLE
Code organization and review for everyone

### ISSUE THREAD

**Issue by weilip1803** [cs2103jan2016-f14-3j/main#49]
Implement software engineering principle and review structure of code.
Graded based on following qualities of your own code.
Following SLAP (IMPORTANT).
Following the coding standard given (IMPORTANT).
Using at least some assertions.
Using at least some logging.
Using at least some unit tests.
Commenting at the right level.
Exception handling.
Neatness and human readability.

**Comment by tanwcw** [comment]
Push t0 v0.5

**Comment by tanwcw** [comment]
Completed.
